volumes:
  pg_security:

services:
  postgres:
    image: postgres:15
    container_name: pg_container
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: security_db
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - pg_security:/var/lib/postgresql/data

  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    container_name: spring_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5433/security_db
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}